# Generated by Django 3.2 on 2023-11-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_feedback_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
