# Generated by Django 3.2 on 2023-11-04 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_orders_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='qty',
        ),
    ]
